POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Nachete",
    "number": "+346987646"
}

###

POST http://localhost:3001/api/persons 
Content-Type: application/json

{
}

###

POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "name": "Nachete"
}


###

POST http://localhost:3001/api/persons 
Content-Type: application/json

{
    "number": "+346987646"
}